name: Buildx branch
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'
    paths-ignore:
      - .github/workflows/build.yml
      - .github/workflows/buildx-latest.yml
      - .github/workflows/buildx-release.yml
      - .github/workflows/dockerhub-description.yml
      - .github/workflows/rust.yml
      - extra
      - _config.yml
      - .gitignore
      - .rustfmt.toml
      - .gitignore
      - example.json
      - LICENSE
      - README.md
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Buildx setup
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Dockerhub login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u mindflavor --password-stdin 2>&1
      - name: Run Buildx
        run: |
          docker buildx build \
            --progress plain \
            --platform=linux/amd64 \
            --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg COMMIT=`git rev-parse --short HEAD` \
            --build-arg VERSION=${GITHUB_REF##*/} \
            -t mindflavor/prometheus-wireguard-exporter:${GITHUB_REF##*/} \
            --push \
            .
      - run: curl -X POST https://hooks.microbadger.com/images/mindflavor/prometheus-wireguard-exporter/TODO || exit 0
