name: Docker build
on:
  pull_request:
    branches: [master]
    paths-ignore:
      - .github/workflows/buildx-branch.yml
      - .github/workflows/buildx-latest.yml
      - .github/workflows/buildx-release.yml
      - .github/workflows/dockerhub-description.yml
      - .github/workflows/rust.yml
      - extra
      - _config.yml
      - .gitignore
      - .rustfmt.toml
      - .gitignore
      - example.json
      - LICENSE
      - README.md
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build .
